Update Gitpipeline

diff --git a/Gitpipeline b/Gitpipeline
--- a/Gitpipeline
+++ b/Gitpipeline
@@ -4,6 +4,8 @@ pipeline {
         stage (build) {
             steps {
                 echo "This is build stage"
+                echo "Test fail stage"
+                sh 'exit 1'
             }
         }
         stage (test) {
